### ISSUE TITLE
import assert from 'assert' don't work with ts@2.6.2

### ISSUE THREAD

**Issue by zaaack** [power-assert-js/espower-typescript#44]
error message:
```sh
assert_1.default is not a function 
```
 Then I tried `import assert from "power-assert"`, it worked, but no fancy power message.

Current workaround is `const assert = require('assert')`

**Comment by teppeis** [comment]
@zaaack `import assert from 'assert'` throws the error. It's by design of TypeScript and Node.js.
Use `import * as assert from 'assert'` or  `const assert = require('assert')`.
